### ISSUE TITLE
Expiration Date in Vehicle Details not retrieved / saved.

### ISSUE THREAD

**Issue by willvalentin** [mgeronimo/CTG-Apply#72]
Steps to replicate
1. Login as Admin
2. Go to Crowdie Dashboard.
3. View All Details or Edit Crowdie Information (any account).

Actual Result:
The expiration date under Vehicle Details is not shown in "View All Details" and displays "00/00/0000" in "Edit Crowdie Information".

Expected Result:
Display correct Expiration Date.
![expdate2](https://cloud.githubusercontent.com/assets/10610837/5814307/11cd8388-a0c5-11e4-8a58-70cb4e4d1e91.PNG)

![expdate1](https://cloud.githubusercontent.com/assets/10610837/5814305/0a8aa4de-a0c5-11e4-9b6b-8c950122c180.PNG)

**Comment by johnarben2468** [comment]
fixed

**Comment by barbacenasmc** [comment]
Edit page already displays correct expiration date but it is still not displayed on view. Please see image below:
Edit page:
![ctg-expiration-date](https://cloud.githubusercontent.com/assets/7791554/5869472/e53ac8c6-a2f4-11e4-89e7-83c0e449da3c.PNG)
View page:
![ctg-view-details](https://cloud.githubusercontent.com/assets/7791554/5869462/b815e3ee-a2f4-11e4-8958-8a175d5d0b84.PNG)

**Comment by Leirum** [comment]
Issue can still be replicated. Expiration Date details was still not shown in viewing Crowdie information.

**Comment by barbacenasmc** [comment]
Issue can still be replicated on view details page:
![image](https://cloud.githubusercontent.com/assets/7791554/6723429/bf592cf2-ce22-11e4-9486-310e685fa1be.png)
